name: Custom Build

on:
  workflow_dispatch:
    inputs:
      cn:
        description: 'Include Chinese version (add "--cn" to build args)'
        required: false
        default: false
        type: boolean
      normal:
        description: 'Remove opinionated features (add "--normal" to build args)'
        required: false
        default: false
        type: boolean
      no_liga:
        description: 'Remove ligatures (add "--no-liga" to build args)'
        required: false
        default: false
        type: boolean
      no_hinted:
        description: 'Build unhinted font (add "--no-hinted" to build args)'
        required: false
        default: false
        type: boolean
      nf_mono:
        description: 'Fixed Nerd Font icon width (add "--nf-mono" to build args)'
        required: false
        default: false
        type: boolean
      feat:
        description: 'Enable features, split by `,`, e.g. "cv01,ss02" (add "--feat feat1,feat2" to build args)'
        required: false
        default: ''
        type: string
      build_args:
        description: 'Other args for build.py'
        required: false
        default: ''
        type: string

permissions:
  contents: write

jobs:
  custom-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: './requirements.txt'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

          # https://github.com/ryanoasis/nerd-fonts/blob/b3c1b0cf424ac32915cf4fd822c3938d4a815566/.github/workflows/release.yml#L144-L166
          if [[ "${{ github.event.inputs.build_args }}" == *"--font-patcher"* ]] || python build.py --dry | jq -e '.nerd_font.use_font_patcher == true' >/dev/null; then
            sudo apt update -y -q
            sudo apt install software-properties-common -y -q
            sudo apt install python3-fontforge -y -q
            sudo apt install fuse -y -q

            curl -L "https://github.com/fontforge/fontforge/releases/download/20230101/FontForge-2023-01-01-a1dad3e-x86_64.AppImage" --output fontforge
            chmod u+x fontforge
            echo Try appimage
            ./fontforge --version
            export PATH=`pwd`:$PATH
            echo "PATH=$PATH" >> $GITHUB_ENV
            echo Try appimage with path
            fontforge --version
          fi
      
      - name: Run custom script
        run: |
          python build.py --nerd-font --cn --feat cv01,cv03,cv07,cv40,cv61,ss03,ss05,ss07,ss08,ss11 --ttf-only
        continue-on-error: true
      - name: Create release
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: No TTF files found in dist/"
            exit 1
          fi
          gh release create "v$(date +%s)" dist/*.ttf --notes-file NOTES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
